### ISSUE TITLE
SetIntermediateCallback bug on macOS and Windows

### ISSUE THREAD

**Issue by dpo** [juan-pablo-vielma/IpoptBuilder#2]
The `SetIntermediateCallback` has an underscore prepended to it on macOS, causing callback registration to fail:
```
dpo:~/dev/julia/Ipopt.jl (test-callback %)$ nm /Users/dpo/dev/julia/Ipopt.jl/deps/usr/lib/libipopt.1.10.10.dylib | grep -i SetIntermediateCallback
00000000000151b0 t _SetIntermediateCallback
```

See https://github.com/JuliaOpt/Ipopt.jl/pull/157.

**Comment by dpo** [comment]
Update: fails on Windows too: https://ci.appveyor.com/project/dpo/nlpmodelsipopt-jl/build/job/9oh5e3hprxkcyh2i#L276 .

**Comment by mlubin** [comment]
This is related to the symbol filtering at https://github.com/JuliaOpt/IpoptBuilder/blob/224ffe686e3a4049ff7117d6f5588a87695792d8/build_tarballs.jl#L45

`SetItermediateCallback` is the only function in the public C API whose name doesn't include `Ipopt`, so it gets filtered unintentionally.
